### PR TITLE
added numpy tutorial

### PR DESCRIPTION
**Pull request by btel**

### CODE REVIEW

**Comment by btel** [comment]
It's my tutorial for Day 1. Should I simply merge it? I am not used to have push access. ;-)

**Comment by jorisvandenbossche** [comment]
Yes, go ahead!

Quickly looked at it:
- for the setup section, this is for downloading data files? It seems it is very few data (in KBs), so I would just add it to the `/data` fir that is already in the Day_1 dir. That saves the participants a step to further download these

**Comment by btel** [comment]
@jorisvandenbossche Yes, it's already in there. But you need to assume that people cloned the repo.

**Comment by jorisvandenbossche** [comment]
Ah, didn't see that. 
Yes, we are going to give the instructions to download the full repo (either by cloning or by downloading it as a zip file) at the beginning of the day. So everybody should have the data then.

**Comment by btel** [comment]
I updated the instruction to tell the student to download the whole repo, but if you explain it anyways, I will skip this part.

**Comment by jorisvandenbossche** [comment]
Yep, it will be in the opening slides (and will put that in a mail as well). I started on those: https://paris-saclay-cds.github.io/python-workshop/#1 (but have to expand it)

**Comment by jorisvandenbossche** [comment]
Something else: what I personally find an important aspect to be familiar with is boolean indexing using a mask. I will certainly see that in the pandas one, but it might be nice to already see that in the numpy part (if you think there is room and would fit somewhere of course)

**Comment by btel** [comment]
I thought about adding boolean indexing, but indeed there is little room. If you think it will be useful for your pandas tutorial I can include it, though.

**Comment by glemaitre** [comment]
See ya tomorrow!!!

**Pull request merged**
