### PR TITLE
[WIP] Add unit testing notebook

### PR DESCRIPTION
**Pull request by aboucaud**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
I would also quickly introduce numpy.testing and pandas.testing

**Comment by aboucaud** [comment]
Don't know about pandas.testing.. what is the difference with numpy.testing ?

**Comment by jorisvandenbossche** [comment]
it just has a `assert_frame_equal` if you want to test a function that should return a dataframe

**Comment by aboucaud** [comment]
Done.

Please run the notebook.

**Comment by jorisvandenbossche** [comment]
Notebook ran fine!

**Comment by jorisvandenbossche** [comment]
There went something wrong with your rebase / merge with master (there were al lot of unrelated changes in the diff), so rebased and force pushed. 

Will merge this, will make it easier to test and integrate everything. Can do further tweaks on master or in new PR when needed.

**Comment by aboucaud** [comment]
Alright.

**Comment by jorisvandenbossche** [comment]
hmm, my internet is letting me down for a moment, will try to push again

**Comment by jorisvandenbossche** [comment]
anyhow, what I just did after fetching your branch was:

```
git fetch upstream
git rebase upstream/master
git push -f
```

**Pull request merged**
